jdbc.driverClassName=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/later

jdbc.username=postgres
jdbc.password=postgres

hibernate.show_sql=true
hibernate.jdbc.time_zone=UTC
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect